config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/homes/about" => "homes#about", as: "about"
  resources :post_images, only: [:new, :create, :index, :show, :edit, :destroy]

  resources :users, only: [:show, :index, :edit, :update]

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :shop_name,presence:true
  validates :body,presence:true,length:{maximum:200}

  def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpeg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :post_images, dependent: :destroy

   def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

 def after_sign_in_path_for(resource)
    user_path(@user)
 end

  def after_sign_out_path_for(resource)
    root_path
  end

protected

def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @post_image = PostImage.find(params[:id])
    # @post_comment = PostComment.new
  end

  def index
    @post_images = PostImage.all
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    if @post_image.save
      redirect_to post_image_path(@post_image), notice: "You have created post successfully."
    else
      @post_images = PostImage.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @post_image.update(post_image_params)
      redirect_to post_image_path(@post_image), notice: "You have updated post successfully."
    else
      render "edit"
    end
  end

  def destroy
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :body, :image)
  end

  def ensure_correct_user
    @post_image = PostImage.find(params[:id])
    unless @post_image.user == current_user
      redirect_to post_images_path
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images
    @post_image = PostImage.new
  end

  def index
    @users = User.all
    @post_image = PostImage.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_image_helper.rb
module PostImageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>

<div class="row">
  <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, class: "btn btn-secondary btn-sm btn-block mb-3 sign_in", method: :post %>
</div>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>meshiterro</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> Users
            <% end %>
          </li>
          <li>
            <%=  link_to post_images_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> Shops
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> Logout
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> Home
            <% end %>
          </li>
          <li>
            <%= link_to about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> sign up
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> login
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/post_images/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>shop</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% post_images.each do |post_image| %>
      <tr>
        <td><%= link_to(post_image.user) do %>
          <% end %>
        </td>
        <td><%= link_to post_image.shop_name,post_image, class: "post_image_#{post_image.id}" %></td>
        <td><%= post_image.body %></td>
        <!--<td class=</%= "favorite-" + book.id.to_s %> >
            </%= render "favorites/btn", book: book %>
        </td>
        <td></%= render "book_comments/counter", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/post_images/_new.html.erb
<%= form_with model:@post_image do |f| %>
  <div class="form-group">
    <%= f.label :shop_name %>
    <%= f.text_field :shop_name, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/post_images/edit.html.erb
<h1>PostImage#edit</h1>
<p>Find me in app/views/post_image/edit.html.erb</p>

app/views/post_images/index.html.erb
<div class='container px-5 px-sm-0'>
  <!--</%= render 'layouts/errors', obj: @book %>-->
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <!--</%= render 'users/info', user: current_user %>-->
      <h2 class="mt-3">New post</h2>
      <%= render 'new', post_image: @post_image %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', post_images: @post_images%>
    </div>
  </div>
</div>

app/views/post_images/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <!--<h2>User info</h2>-->
      <!--</%= render 'users/info', user: @book.user %>-->-->
      <h2 class="mt-3">New book</h2>
      <%= render 'new', post_image: PostImage.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>shop detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@post_image.user) do %>
            <%= @post_image.user.name %>
            <% end %>
          </td>
          <td><%= link_to @post_image.shop_name, @post_image %></td>
          <td><%= @post_image.body %></td>
          <!--<td class=</%= "favorite-" + @book.id.to_s %> >-->
            <!--<?%= render "favorites/btn", book: @book %>-->
          <!--</td>-->
          <!--<td class="book-comments-counter">-->
            <!--</%= render "book_comments/counter", book: @book %>-->
          <!--</td>-->
          <% if @post_image.user == current_user %>
            <td><%= link_to 'Edit', edit_post_image_path(@post_image), class: "btn btn-sm btn-success edit_post_image_#{@post_image.id}" %></td>
            <td><%= link_to 'Destroy', @post_image, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_post_image_#{@post_image.id}" %></td>
          <% end %>
        </tr>
      </table>

      <!--<div class="book-comments-index">
        </%= render "book_comments/index", book: @book %>
      </div>

      </%= render "book_comments/form", book: @book, book_comment: @book_comment %>-->

    </div>
  </div>
</div>

app/views/users/show.html.erb
show